### ISSUE TITLE
Send ‘configuration’ dict during ‘set_initial’ phase

### ISSUE THREAD

**Issue by Debilski** [ASPP/pelita#128]
Some of the current and future `game_state` keys do not change during the game (layout_name, seed; possibly a few more) and might not need to be passed at every move. (Only during `set_initial`.)
We could add a `configuration` dict to GameMaster to hold those values, which would also separate pure configuration values from the `game_state`.

**Comment by otizonaizit** [comment]
This is not needed anymore.
