### ISSUE TITLE
Make number of bots/teams more variadic

### ISSUE THREAD

**Issue by Debilski** [ASPP/pelita#140]
This is a low priority issue but nonetheless…

Currently, pelitagame only works with the ‘classic’ two bots–two teams setup. This restriction should be lifted. In the short term we can at least allow teams with more or less than two bots. (And also situations where three bots play against one.)

This involves a small bit of layout fixing but should be doable. (The layout loading lib assumes a bit much about the bot ids.)

The idea is of course that matches with three or more bots each would be far more interesting as one can then have two defenders teaming up. (One defender alone is too weak without dead ends.)

**Comment by otizonaizit** [comment]
OK, after 7 years we have to admit defeat. We are going to have 2 teams of 2 bots each.
