### ISSUE TITLE
pelitagame --help is littered

### ISSUE THREAD

**Issue by otizonaizit** [ASPP/pelita#166]
There is already too much information in the `--help` output to the `pelitagame` script. And more is to come for every new feature. We could:

1) have a man page
2) have subhelp options: `--help-debug`, `--help-server`, `--help-rules`, `--help-teams`, and of course a `--help-all` that prints them all

pros for 1) are that this is the standard solution, cons that as we don't expect people to install pelita -- not at this stage, at least -- it may be quite hard to _display_ the man page. 
pros for 2) are that it is easier to use and implement, cons that it may be difficult to find proper `--help`` categories to give a structure to the help...

**Comment by Debilski** [comment]
Fixed with #535.
