### ISSUE TITLE
Add animated game to front page

### ISSUE THREAD

**Issue by Debilski** [ASPP/pelita#220]
Maybe it would be nice to have a gameplay animation instead of the static image on the front page. What should it be: GIF / js + PNGs / js + live animation with canvas?

**Comment by Debilski** [comment]
![Example](https://cloud.githubusercontent.com/assets/216179/17270213/03eb921e-565e-11e6-8dde-db68efd5a8fe.gif)

**Comment by otizonaizit** [comment]
This is probably not really needed.
