### ISSUE TITLE
Hexagonal grid (Pelita ⬡)

### ISSUE THREAD

**Issue by Debilski** [ASPP/pelita#221]
⬡⬢⬡

Having read this article on hexagonal grids ( http://www.redblobgames.com/grids/hexagons/ ), I can’t get the idea out of my head of eventually having a version running a hexagonal universe. Algorithm-wise, this would not be too different: all A\* things would still apply (more connections mean more calculation time, though). It’s half-way to allowing diagonal moves.

One possible alteration could be to allow only one bot per hex field (in a Civ V way) which might or might not turn out to be interesting.

Main advantage is of course: Hex grids are way cooler than square grids and everybody who sees a screenshot of one will be wanting to try out our little game. :)

⬡⬢⬡

**Comment by otizonaizit** [comment]
This is another of the series: YAGNI
