### ISSUE TITLE
Bug in pelitagame when both teams use the same module name

### ISSUE THREAD

**Issue by Debilski** [ASPP/pelita#272]
pelitagame only uses the first module for both players when both module names are equal.

**Comment by Debilski** [comment]
This is a really unfortunate bug. We could avoid it by running all clients as separate processes (which would mean that the player would have to wrap the user’s code complete with command line arguments for ports). This means of course more API/protocol stuff but it also means that Python players are no longer special. They’d function exactly as players written in other languages. Thoughts: @otizonaizit

**Comment by venthur** [comment]
I suggested this feature years ago. Again, I suggest to look at http://aichallenge.org/ and the way they implemented the IPC. It is basically round-based and uses STDIN and STDOUT. This allows also for programming language independent players. Have a look at it, it is really not that complicated.

**Comment by Debilski** [comment]
I know, @venthur . The question is whether the error messages are then good enough whenever something goes wrong. When we run players through pelitagame, we can at least tell whether something went wrong during, say, the import stage of a user’s player. When it is just command line, errors may become really opaque.

**Comment by otizonaizit** [comment]
I think running the players as separate processes seems the cleaner solution (but still you'll have to disambiguate the team names in the viewer, wouldn't you?). Reworking the whole communication protocol is a tangent issue. I personally don't see what the advantage would be, but the discussion should happen on a different issue or on the mailing list...

**Comment by Debilski** [comment]
The team name gets set through the zmq API (or in Python code through the `Player` API, resp.) so this would have to be configured by the user anyway.
It is not the whole protocol that would have to be redone; mostly some initial confirmation checks would be useful and some timeout handling. This of course introduces some delay when things go wrong.

The most important part would be a command line spec. Ie.

    pelitagame ./my_player.py:factory

will have to result in a call to

    ./my_player.py --factory factory --zmqconn tcp://127.0.0.1:54321

or similar. And ideally this should also work on Windows…

**Comment by Debilski** [comment]
Removing module loading related stuff from `pelitagame` and putting it into a separate script `pelita_module.py` which is then executed in a subprocess by `pelitagame` seems to be working without too much command line hassle. (There is a risk of diverging interfaces.) It may even give us the debug mode for free.

I’ll keep looking into whether a zmq free `Popen.communicate` solution gives us some advantages.
