### ISSUE TITLE
pelitagame is vulnerable to failures in the player’s factory

### ISSUE THREAD

**Issue by Debilski** [ASPP/pelita#273]
```
$ cat myplayer.py
def factory():
    import sys
    sys.exit(0)
```

Now `pelitagame myplayer.py` just silently exits (one could even print to stdout before that and irritate the tournament script).

**Comment by Debilski** [comment]
Has been fixed but needs a test.

**Comment by otizonaizit** [comment]
This is not a problem anymore.
