### ISSUE TITLE
Generate and publish documentation with travis

### ISSUE THREAD

**Issue by Debilski** [ASPP/pelita#278]
Is there a reason why we don’t do this?

**Comment by stefanv** [comment]
Nope, someone just needs to set it up.  But, I guess in this case something like readthedocs would work as well?

**Comment by Debilski** [comment]
Guess one reason is that it would kind of spam the gh-pages branch if we did it on every commit automatically.

**Comment by Debilski** [comment]
Closed in https://github.com/ASPP/pelita/pull/292

**Comment by Debilski** [comment]
Scripts may need some more refinement, though.
