### ISSUE TITLE
Replace `time()` in timeout checks with `monotonic()` on Python 3

### ISSUE THREAD

**Issue by Debilski** [ASPP/pelita#279]
This is done wrong in loads of projects. We should provide a good example of doing it correctly.

**Comment by stefanv** [comment]
Rally the troops!

... and thanks, I learnt something new :)

**Comment by Debilski** [comment]
Only problem is the this means littering the code with things like

    time_start = time.monotonic() if six.PY3 else time.time()

and then I’m not sure anymore this is really worth implementing. :)

**Comment by stefanv** [comment]
Why not just implement a utility function somewhere?

**Comment by Debilski** [comment]
Guess that’s slightly over-engineered:

    @contextmanager
    def time_monochronic():
        ts = time.monotonic() if six.PY3 else time.time()
        yield lambda: (time.monotonic() if six.PY3 else time.time()) - ts

    with time_monochronic() as tm:
        print(tm())
        time.sleep(1)
        print(tm())
        print(tm())
