### ISSUE TITLE
[discussion] Syntax: Food in maze[pos]

### ISSUE THREAD

**Issue by Debilski** [ASPP/pelita#281]
Should we get rid of the syntax

    Food in maze[pos]

Since Python offers no first-class support for singleton symbols[*], we currently have `Food`, `Free`, and `Wall` defined as single-character strings and `maze[pos].__contains__` is overloaded to return a multi-character string. While the syntax looks quite nice, I do not really like its underlying representation. Additionally, since it is not possible to query

     Bot(1) in maze[pos]

it is unclear, if special casing the food (which does not even differentiate between enemy and own food) is really worth it.

I don’t have the students’ repositories with me right now, so I cannot make any guesses how often this syntax has been used (in the tutors’ repo it is only used by Pietro and me in three lines altogether) but in many cases, I’d think the stateful helper methods on `Player` provide enough information for the neighbourhood already and for global scales, we’d probably resort to boolean matrices `maze.food[pos]`. (Exact procedure might vary depending on internal optimisations regarding the data structure.)

Is there anyone who especially likes the old syntax?

[*]: Alternatives would be classes, which are weird because they could be initialised (which would be senseless) or objects, which would not be singletons and we’d have to do instance checks.

**Comment by keszybz** [comment]
On Fri, May 22, 2015 at 07:15:12AM -0700, Rike-Benjamin Schuppner wrote:
> Should we get rid of the syntax
> 
>     Food in maze[pos]
> 
> Since Python offers no first-class support for singleton symbols[*],
There's enum in Python 3, backported as a module to Python 2, iirc.
Is this what you mean by singleton symbols?

> we currently have `Food`, `Free`, and `Wall` defined as single-character strings and `maze[pos].__contains__` is overloaded to return a multi-character string. While the syntax looks quite nice, I do not really like its underlying representation. Additionally, since it is not possible to query
> 
>      Bot(1) in maze[pos]
> 
> it is unclear, if special casing the food (which does not even differentiate between enemy and own food) is really worth it.
> 
> I don’t have the students’ repositories with me right now, so I cannot make any guesses how often this syntax has been used (in the tutors’ repo it is only used by Pietro and me in three lines altogether) but in many cases, I’d think the stateful helper methods on `Player` provide enough information for the neighbourhood already and for global scales, we’d probably resort to boolean matrices `maze.food[pos]`. (Exact procedure might vary depending on internal optimisations regarding the data structure.)
> 
> Is there anyone who especially likes the old syntax?
I think it is more important for the code to be simple than to squeeze out
every last bit of notation. So yeah, maze.food[pos] looks reasonable.

Zbyszek

**Comment by Debilski** [comment]
Ah, yes. Enums would be an option, too. I’d prefer a symbol which is its own value, though, but that’s a minor thing.

I’ll start by revising the backend structure a bit and we’ll see what API comes out from that. Backend restructuring should eventually lead to better JSON representations which means better 3rd party integration of non-Python tools (honestly, it is not as stupid and useless as it may sound).

**Comment by Debilski** [comment]
Actually, I think most people go for the food helper methods on universe anyway. We could probably get rid of `maze.food` completely and have the maze only store the walls.

**Comment by Debilski** [comment]
Ok. I think, the decision is made (have the private code ready and don’t want to change it anymore :) ).

One thing to argue about would be how to query for food and walls, respectively: Currently, the maze is a 2d boolean matrix and the food is a list of positions. (Kind of what I think are the natural representations for either.)
Therefore, the check for walls goes like `if maze[x, y]: # is wall` and `if (x, y) in food_list: # is food`. Our dozens of helper methods of course lead to dozens of alternatives…

**Comment by keszybz** [comment]
On Mon, May 25, 2015 at 03:06:57PM -0700, Rike-Benjamin Schuppner wrote:
> Ok. I think, the decision is made (have the private code ready and don’t want to change it anymore :) ).
> 
> One thing to argue about would be how to query for food and walls, respectively: Currently, the maze is a 2d boolean matrix and the food is a list of positions. (Kind of what I think are the natural representations for either.)
> Therefore, the check for walls goes like `if maze[x, y]: # is wall` and `if (x, y) in food_list: # is food`. Our dozens of helper methods of course lead to dozens of alternatives…

Less would be more in this case I think, all those helpers are confusing.
So if you remove anything I'm in favour ;)
