### ISSUE TITLE
Decouple initial and current position in layout format

### ISSUE THREAD

**Issue by Debilski** [ASPP/pelita#282]
Currently, when reading a layout, figures 0, 1, 2, 3 are used to specify both the current position of a bot and its initial (and respawn) position. This may lead to unintended results in tests when a respawn position is mistakenly defined as being inside the enemy team’s zone: https://github.com/ASPP/pelita/issues/203

Since we probably don’t want to give up easily on the ASCII representation and definition of a layout, things become slightly harder to solve.

Here is one proposal, (but I’m not 100% sure about the randomness):

Allow for an arbitrary number of initial positions per team (defined as `A` for team 0, `B` for team 1) and killed bots are respawned at a random position.
On startup, unless otherwise specified, the bots are positioned in a way that the number of bots at each initial position differs by at most one. – NB: This means that it is undefined in layout which bot starts!

Thus, we define a maze as

```
##################
#  #..    .  #  B#
#.... ..   .    B#
#  #    #######  #
#  #######    #  #
#A    .   .. ....#
#A  #  .    ..#  #
##################
```

and an in-game situation (yes, this situation is impossible to create from the above game – please delete some of the food pellets mentally) as

```
##################
#  #.. 1  .  #  B#
#.... ..   .    B#
#  #    #######  #
#  #######3   #  #
#A  2 .   .. ....#
#A  #  .   0..#  #
##################
```

This still does not solve the representation when a bot or a home position is to be defined as sitting on a food pellet (Maybe go unicode then: http://en.wikipedia.org/wiki/Enclosed_Alphanumerics) and we have the curious situation of having potentially more variables for the number of teams than for the number of bots.

Thoughts?

**Comment by otizonaizit** [comment]
I don't like the randomized respawn position at all: this is inserting a huge random factor in a game that had almost none (or at least, the randomness was only restricted to maze layout and food, which are equal for both teams). 
I am not sure that issue #203 is worth fixing: this only happens in a test where you esplicitly do not follow the convention that bots are respawned at the origin. As such is not a real problem during a real game. 
So, all in all, I would close #203 as wont-fix and leave bots positions and their representation intact.

**Comment by Debilski** [comment]
I agree that #203 is not a problem during real game but for writing tests I think it does introduce a problem because you basically have no simple way to define and test in-game situations properly (without explicitly setting either the current or the initial positions in code). Being able to define both independently in ASCII would be a very welcome addition also for our own test suite. [*]

I’m undecided on the randomness. I found that it gave the nicest ASCII representation and don’t necessarily think having some randomness rules would be a bad thing per se. (I also liked the idea of having a bunch of respawn points all across the maze.) But for the school, having it all symmetrical makes sense as well.

Randomness is no issue, of course, when you only define one respawn position per maze…

[*] The first tests people write is to check what happens when a bot sits on food and when two bots face each other at the border. This quickly becomes pathological when the respawn positions are not shifted somewhere else and I think we should make the definition of this as simple as possible.

**Comment by otizonaizit** [comment]
> I agree that #203 is not a problem during real game but for
> writing tests I think it does introduce a problem because you
> basically have no simple way to define and test in-game situations
> properly (without explicitly setting either the current or the
> initial positions in code). Being able to define both
> independently in ASCII would be a very welcome addition also for
> our own test suite. [*]
I am not sure you have to go through ASCII or Unicode gimmicks to
allow for it. An helper method, maybe just in the tests, would solve
the problem too. The keep it simple thing seems to be appropriate
here.

> I’m undecided on the randomness. I found that it gave the nicest
> ASCII representation and don’t necessarily think having some
> randomness rules would be a bad thing per se. (I also liked the
> idea of having a bunch of respawn points all across the maze.) But
> for the school, having it all symmetrical makes sense as well.
> 
> Randomness is no issue, of course, when you only define one
> respawn position per maze…
Well, my take is that there's no point in risking that randomness
potentially *does* some harm. Just avoid it and that's it. 

> [*] The first tests people write is to check what happens when
> a bot sits on food and when two bots face each other at the
> border. This quickly becomes pathological when the respawn
> positions are not shifted somewhere else and I think we should
> make the definition of this as simple as possible.
Exactly, so have an helper method for it. So that the ASCII
representation stays simple enough that does not require any further
explanation…

**Comment by Debilski** [comment]
Half-fixed. We now have an algorithm for the initial positions.
