### ISSUE TITLE
Why are we storing all previous universes in AbstractPlayer?

### ISSUE THREAD

**Issue by Debilski** [ASPP/pelita#285]
I think we made this a conscious decision back then but I don’t know anymore what was the reasoning behind it. Has this ever been used?

**Comment by otizonaizit** [comment]
> I think we made this a conscious decision back then but I don’t
> know anymore what was the reasoning behind it. Has this ever been
> used?
We don't know if it has ever been used, but it is a way to make it
easier to track history, isn't it?

**Comment by Debilski** [comment]
> Am 27.05.2015 um 15:15 schrieb Tiziano Zito <notifications@github.com>:
> 
> > I think we made this a conscious decision back then but I don’t
> > know anymore what was the reasoning behind it. Has this ever been
> > used?
> We don't know if it has ever been used, but it is a way to make it
> easier to track history, isn't it? 

But why would someone want this? :)

It is also kind of implemented in a insufficient way as it only tracks the universe according to one player only. If you want to do serious analyses you’ll have to add code which extracts both players’ histories.

**Comment by otizonaizit** [comment]
> > We don't know if it has ever been used, but it is a way to make it
> > easier to track history, isn't it? 
> 
> But why would someone want this? :)
This is not a serious question, isn't it? I mean, because maybe your
actions will depend on the previous states? 

> It is also kind of implemented in a insufficient way as it only
> tracks the universe according to one player only. If you want to
> do serious analyses you’ll have to add code which extracts both
> players’ histories.
Which to me sounds more an argument for improving the implementation
instead of ditching it...

**Comment by Debilski** [comment]
> Am 27.05.2015 um 15:39 schrieb Tiziano Zito <notifications@github.com>:
> 
> > > We don't know if it has ever been used, but it is a way to make it
> > > easier to track history, isn't it? 
> > 
> > But why would someone want this? :)
> This is not a serious question, isn't it? I mean, because maybe your
> actions will depend on the previous states? 

Sorry, shouldn’t have sounded the way it’s been written…

Still, I’m unsure if people – in general – would need access to more than the bot’s previous positions. But okay. Maybe you’re right and having a complete copy of the universe is something which does no harm if it’s there.

Anyway, there is a slight API argument against it: When there is only current_uni, there is in principle no need to know anything about the API methods on CTFUniverse (apart from maze). Everything is in AbstractPlayer. Prominently implementing the universe history means we’ll have to explain much more about it (and confuse users).

> > It is also kind of implemented in a insufficient way as it only
> > tracks the universe according to one player only. If you want to
> > do serious analyses you’ll have to add code which extracts both
> > players’ histories.
> Which to me sounds more an argument for improving the implementation
> instead of ditching it…

That’s not too easy, though.

**Comment by otizonaizit** [comment]
> Still, I’m unsure if people – in general – would need access to
> more than the bot’s previous positions. But okay. Maybe you’re
> right and having a complete copy of the universe is something
> which does no harm if it’s there.
> 
> Anyway, there is a slight API argument against it: When there is
> only current_uni, there is in principle no need to know anything
> about the API methods on CTFUniverse (apart from maze). Everything
> is in AbstractPlayer. Prominently implementing the universe
> history means we’ll have to explain much more about it (and
> confuse users).
OK, then I think it is fair to ask that the PR removing this
also adds an example to the documentation on how to properly keep
track of things, if you want to learn from history or base your
decision on something else than previous bot positions…

**Comment by Debilski** [comment]
Ok, I’ll think about this when potentially revising the API.

**Comment by Debilski** [comment]
New API deals with that.
