### ISSUE TITLE
Change the ‘coding conventions’

### ISSUE THREAD

**Issue by Debilski** [ASPP/pelita#299]
This is rather outdated:
# Coding conventions
- Docstrings should follow the `Numpy convention
  <https://github.com/numpy/numpy/blob/master/doc/HOWTO_DOCUMENT.rst.txt>`_
- Use old-style `print` statement (not the function)
- For internal messages, use the `logging` module with an appropriate logging
  level, which makes their appearance completely configurable.
- Use old-style format-string, i.e. `"%s" % (val))` instead of
  `"{0}".format(val)`
# Changelog

:v0.1.1 -- 2012-05-23:
    \* Bugfix/Maintenance Release
    \* tying together loose ends
:v0.1.0 -- 2011-09-21:
    \* Initial Release
    \* for St. Andrews Summerschool

**Comment by otizonaizit** [comment]
Obsolete.
