### ISSUE TITLE
Are NumPy style docstrings still cool or should we use Google style?

### ISSUE THREAD

**Issue by Debilski** [ASPP/pelita#355]
I think NumPy style is slightly too verbose (uses too many lines), especially for short functions. That said, the Google style is also rather practical than beautiful. Are we going to be strict about what to use?

http://www.sphinx-doc.org/en/stable/ext/example_google.html#example-google

**Comment by otizonaizit** [comment]
On Fri 05 Aug, 07:33, Rike-Benjamin Schuppner <notifications@github.com> wrote:
>Are we going to be strict about what to use?

yes.

**Comment by Debilski** [comment]
Both are kind of ugly

    def cmd_unsplit(cmd):
        """
        Translates a list of command arguments into bash-like ‘human’ readable form.
        Pseudo-reverses shlex.split()

        Example
        -------
            >>> cmd_unsplit(["command", "-f", "Hello World"])
            "command -f 'Hello World'"

        Parameters
        ----------
        cmd : list of string
            command + parameter list

        Returns
        -------
        string
        """
        return " ".join(shlex.quote(arg) for arg in cmd)


    def cmd_unsplit(cmd):
        """
        Translates a list of command arguments into bash-like ‘human’ readable form.
        Pseudo-reverses shlex.split()

        Example:
            >>> cmd_unsplit(["command", "-f", "Hello World"])
            "command -f 'Hello World'"

        Args:
            cmd (list of string): command + parameter list

        Returns:
            string
        """
        return " ".join(shlex.quote(arg) for arg in cmd)

**Comment by otizonaizit** [comment]
On Fri 05 Aug, 07:56, Rike-Benjamin Schuppner <notifications@github.com> wrote:
>Both are kind of ugly

I know and I agree. In the future most of this will be addressed by type 
annotations anyway. But here we are supposed to teach the standards, and 
in scientific Python the standard is NumPy style, ugly or not…

**Comment by Debilski** [comment]
> Am 05.08.2016 um 17:00 schrieb Tiziano Zito <notifications@github.com>:
> 
> On Fri 05 Aug, 07:56, Rike-Benjamin Schuppner <notifications@github.com> wrote:
> >Both are kind of ugly
> 
> I know and I agree. In the future most of this will be addressed by type 
> annotations anyway. But here we are supposed to teach the standards, and 
> in scientific Python the standard is NumPy style, ugly or not…

Type annotations are even uglier than Python’s docstring conventions. ;)
