### ISSUE TITLE
Disallow int ids for the tournament teams

### ISSUE THREAD

**Issue by Debilski** [ASPP/pelita#369]
Currently, teams in the tournament are internally referenced by a configurable id value that defaults to an integer (coming from `enumerate`). This was done to avoid parsing back and forth between str and int (which in my opinion opens another set of subtle bugs) but leads to the situation where we have a:

    def winner_of_match(id1: TeamId, id2: TeamId) -> Union[TeamId, bool, None]

where the outcome is either a `TeamId` for the winner or `False` in case of a draw. (`None` denotes an unplayed/unfinished match; `True` is an invalid value).

The API may there for never be used in an implicit boolean context

    # check if there was a draw *
    if not winner_of_match(t1, t2): # will be true for values of 0: TeamId

but must be used explicitly

    # check if there was a draw
    if winner_of_match(t1, t2) is not False:

Alternative solutions would be to return an explicitly rich type (`namedtuple`?) for the states.

**Comment by keszybz** [comment]
I'd try the following:
```
class Draw:
   __repr__ = lambda self: self.__class__.__name__
Draw = Draw()
...
if winner_match() not in {Draw, None}:
    ...
```
IMHO this is nicely explicit and unlikely to to cause confusion.

**Comment by Debilski** [comment]
I like it but I’d question that this style widely accepted. Otherwise, why does not everyone do it like this? Can we make a PEP for abstract data types?

Anyway, the problem is not really solved as long is `None` is still a possible value.

**Comment by keszybz** [comment]
On Tue, Sep 13, 2016 at 03:57:00AM -0700, Rike-Benjamin Schuppner wrote:
> I like it but I’d question that this style widely accepted. Otherwise, why does not everyone do it like this? Can we make a PEP for abstract data types?
> 
> Anyway, the problem is not really solved as long is `None` is still a possible value.

Where exactly do the IDs come from? Shouldn't they be generated
automatically?

**Comment by Debilski** [comment]
Both is possible. Either one specifies it explicitly with `id: blablateam` in the `.yaml` or it is the index of the team list. Yes, we could just change the numerical id to a string …

**Comment by otizonaizit** [comment]
>IMHO this is nicely explicit and unlikely to to cause confusion.

nicely explicit? Hm, I think we have very different interpretations of 
what explicit and nice mean ;-)

**Comment by keszybz** [comment]
But why customize the ids? Let's just drop this functionality and always use ints.

@tiziano: yeah, for me x == Draw, or x is Draw, where Draw cannot be mistaken with anything else or created by mistake, and has proper representation in traceback and similar, is explicit.

**Comment by Debilski** [comment]
> Am 13.09.2016 um 13:17 schrieb Tiziano Zito <notifications@github.com>:
> 
> >IMHO this is nicely explicit and unlikely to to cause confusion.
> 
> nicely explicit? Hm, I think we have very different interpretations of 
> what explicit and nice mean ;-)

It is easier to understand with a decorator:

    def singleton(cls):
        cls.__repr__ = lambda self: self.__class__.__name__
        return cls()

    @singleton
    class Draw:
        pass


;)

**Comment by keszybz** [comment]
Sure, that should work too ;)

**Comment by otizonaizit** [comment]
>@tiziano: yeah, for me x == Draw, or x is Draw, where Draw cannot be 
>mistaken with anything else or created by mistake, and has proper 
>representation in traceback and similar, is explicit.
Sure, but it is the definition of the Draw object which looks like 
Python pornography. Note that short strings are also a kind of 
"singletons" in Python: they are interned, they are immutable, and

if winner == 'draw':
   do_thing()
elif winner is None:
   handle_crash()
else:
   give_points_to(winner)

seems extremely readable, usable, and efficient to me...

**Comment by Debilski** [comment]
Customisation is used when the computer voice announces the names:

‘group0, members are…, tutor-group0, members are’

And maybe more importantly, it serves as reference in the state.yaml file. So that when something goes wrong one does not have to count all indexes.

**Comment by Debilski** [comment]
> Am 13.09.2016 um 13:28 schrieb Tiziano Zito <notifications@github.com>:
> 
> >@tiziano: yeah, for me x == Draw, or x is Draw, where Draw cannot be 
> >mistaken with anything else or created by mistake, and has proper 
> >representation in traceback and similar, is explicit.
> Sure, but it is the definition of the Draw object which looks like 
> Python pornography. Note that short strings are also a kind of 
> "singletons" in Python: they are interned, they are immutable, and
> 
> if winner == 'draw':
> do_thing()
> elif winner is None:
> handle_crash()
> else:
> give_points_to(winner)
> 
> seems extremely readable, usable, and efficient to me…

Unless the team is called 'draw‘ …

**Comment by otizonaizit** [comment]
>Unless the team is called 'draw‘ …

Ok, then disallow the name 'draw' or insert an invisible UTF-8 character 
after 'draw' so the no-one can name a team like that (team names must be 
ASCII, right?)...

**Comment by keszybz** [comment]
And you call this explicit ?! ;)

**Comment by Debilski** [comment]
Come on, let’s just disallow `0` and it is fixed. :)
