### ISSUE TITLE
Add a warning to the tournament that log files be copied

### ISSUE THREAD

**Issue by Debilski** [ASPP/pelita#373]
Otherwise we will always forget about the animations.

**Comment by otizonaizit** [comment]
Posting to a website is also possible, but again, it depends on network working during the tournament, website getting files without authentication, etc...
I think a visual warning at the end of the tournament is enough. The person running the tournament will see and then just rsync the files wherever she wants...

**Comment by keszybz** [comment]
What about copying the files to remote server if possible, and emitting a big loud warning if that fails? This seems much more user friendly and convenient.

**Comment by otizonaizit** [comment]
On Tue 13 Sep, 04:35, Zbigniew Jędrzejewski-Szmek <notifications@github.com> wrote:
>What about copying the files to remote server if possible, and emitting 
>a big loud warning if that fails? This seems much more user friendly 
>and convenient.

Sure, but the server needs to be configurable, right? And without 
authentication?

**Comment by keszybz** [comment]
I'd use a "well-known" place, maybe paste.fedoraproject.org, or something else if easier. The URL would be printed in output, and otherwise can be extracted from http://paste.fedoraproject.org/rss/.
