### ISSUE TITLE
Shall we detect and punish loops? How?

### ISSUE THREAD

**Issue by Debilski** [ASPP/pelita#376]
None of the solutions I can come up with sounds really convincing but I am open for alternatives.

**Comment by otizonaizit** [comment]
Oh well, I am not sure there's much point in punishing loops. Some bots have randomness that allows them to escape a loop if they stay in it long enough (Munichorga had something like this), so I don't see any robust detection mechanism for loops either. We could discuss about lowering the timeout: three seconds is too much, given that some bots take 2.5 sec for every move, which makes for a total game lenght of 12 minutes... What about setting the timeout to 1 sec? We may allow for 10 timeouts instead of 5 if we need to relax this a bit.

**Comment by keszybz** [comment]
On Tue, Sep 13, 2016 at 12:28:11AM -0700, Tiziano Zito wrote:
> Oh well, I am not sure there's much point in punishing loops. Some bots have randomness that allows them to escape a loop if they stay in it long enough (Munichorga had something like this), so I don't see any robust detection mechanism for loops either. We could discuss about lowering the timeout: three seconds is too much, given that some bots take 2.5 sec for every move, which makes for a total game lenght of 12 minutes... What about setting the timeout to 1 sec? We may allow for 10 timeouts instead of 5 if we need to relax this a bit.

Lowering the timeout sounds good. One can do parallel computing in the
background if necessary ;)

**Comment by Debilski** [comment]
But getting a random move might seem unfair then.

**Comment by Debilski** [comment]
Also, if you have a maze with only few walls, path analysis will quite suddenly take a while longer. So one might not even be aware of it.

**Comment by otizonaizit** [comment]
>But getting a random move might seem unfair then.
I don't think so. It does not seem unfair now, so it will not seem 
unfair if we changed the default timeout...

**Comment by otizonaizit** [comment]
>Also, if you have a maze with only few walls, path analysis will quite 
>suddenly take a while longer. So one might not even be aware of it.
OK, we could be more scientific with this too. We have now a A-star that 
works, we should check that BSF also works. We profile the two and 
verify how long it takes for a tournament-sized maze without any walls 
to calculate the farthest path on a slowish laptop. We take this number, 
multiply by two, ceil it. The result is the new timeout. Agreed?

**Comment by Debilski** [comment]
I agree we should test it. But unscientifically, I’d say we only decide after I have had a look at the results. :)

**Comment by Debilski** [comment]
We could also add a rule concerning the maximum time a player uses

**Comment by otizonaizit** [comment]
YAGNI
