### ISSUE TITLE
People still get confused about that __init__.py thing? Change it?

### ISSUE THREAD

**Issue by Debilski** [ASPP/pelita#379]
Right now we have the factory in **init**.py, which makes it easier for us to standardise what to call in the tournament. However, many students seemingly struggle slightly with the concepts behind that decision. The disconnect to that increases when they see that the internal player implementations do not in fact use a factory but are randomly assigned with some completely different mechanism. (The files with the default players however still contain a `SimpleTeam` factory which again adds to the confusion.)

One first step might be: make it mandatory to use the (or a) factory

```
./pelitagame ../groupN/team/:factory
```

that at least makes it clear what is going on and allows for people to easily understand how to use different factories.

**Comment by Debilski** [comment]
Other ideas? Or am I the only one concerned about this?

**Comment by otizonaizit** [comment]
On Tue 13 Sep, 07:10, Rike-Benjamin Schuppner <notifications@github.com> wrote:
>Other ideas? Or am I the only one concerned about this?

I understand your concerns, but I think that this is more a problem with 
the documentation than a problem with the implementation. What happened 
with #333? I think it would be easier to just have a tournament FAQ in 
the docs, explicitly explaining all of this and making references to the 
appropriate pages on the pelita docs, and then point the students to the 
FAQ. That would make it easier for us to add additional questions, when 
they pop up during the school...

**Comment by Debilski** [comment]
#333 is buried in a git stash somewhere…

**Comment by Debilski** [comment]
Might indeed be less of a concern when we are installable with pip because there will be much less confusion then about the paths and stuff.

**Comment by otizonaizit** [comment]
Obsoleted.
