### ISSUE TITLE
Cleanup GitHub issues and put labels

### ISSUE THREAD

**Issue by otizonaizit** [ASPP/pelita#382]
Now that we have some external users we need to be more diligent with our stuff. The list of issues is disproportionally long, with many issues being either obsolete (e.g., #37) or just jokes (e.g., #338, #370). The list should be cleaned up, end every issue needs at least one label, so that it is a bit easier to navigate the list. This also makes it easier to find assignments for people who want to contribute.
Unless someone speaks up, I'll go through the list and kill/label/move issues. @Debilski: as you are doing and have done most of the work, it is probably wiser if you first sweep through the issues and label the ones you care about most. @Debilski, @keszybz, @jakobj: What do you think?
@esc: I assume you don't care any more about the project? If instead you care, your opinion is of course highly appreciated :-)

**Comment by Debilski** [comment]
How is #370 a joke? #37 is still in there as a reminder to clean the demo repo and remove what is obsolete.

It may not seem so but I regularly close old issues. :)

**Comment by Debilski** [comment]
Could not resist: https://twitter.com/debilski/status/775709770422575104 ;)

**Comment by esc** [comment]
What project?! ;)

On 13 September 2016 16:47:26 CEST, Tiziano Zito <notifications@github.com> wrote:
>Now that we have some external users we need to be more diligent with
>our stuff. The list of issues is disproportionally long, with many
>issues being either obsolete (e.g., #37) or just jokes (e.g., #338,
>#370). The list should be cleaned up, end every issue needs at least
>one label, so that it is a bit easier to navigate the list. This also
>makes it easier to find assignments for people who want to contribute.
>Unless someone speaks up, I'll go through the list and kill/label/move
>issues. @Debilski: as you are doing and have done most of the work, it
>is probably wiser if you first sweep through the issues and label the
>ones you care about most. @Debilski, @keszybz, @jakobj: What do you
>think?
>@esc: I assume you don't care any more about the project? If instead
>you care, your opinion is of course highly appreciated :-)
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/ASPP/pelita/issues/382

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by jakobj** [comment]
I agree that it makes sense to clean up the issues a bit, a few do seem kind of old and more like reminders to ourselfs (e.g., #187 ;) ) than real issues related to the code. Should we maybe add a `remove?` label that people who don't feel comfortable deleting issues (like me) could use to signal that we think an issue should be removed?

**Comment by Debilski** [comment]
Actually, I consider #187 as reasonably fixed after last week.

**Comment by Debilski** [comment]
Hehe, https://github.com/ASPP/pelita/issues/322

**Comment by Debilski** [comment]
@otizonaizit will surely not like how many new labels I had to introduce. :)

**Comment by otizonaizit** [comment]
I knew a shitstorm was going to come, but I have to admit I did **not** predict the `Meta` label, @Debilski. Anyway, since you seem to enjoy the labels, I will change the colors such that the labels that matter most are more visible, i.e. `Needs test/review`, `TODO`, `Should have`, `Nice to have`, and maybe `Docs`. The rest indicates classification and not action, but I want the labels to indicate **what** you have to do. Classification is useful, but I am not sure it helps a lot to know what are the most urgent things, what is a task that you can assign to someone, what is a purely hypothetical feature.  Anyway, should I assume that you don't care about the issues that are not labeled? Or should I start a discussion for all those I think can go?

**Comment by Debilski** [comment]
I am not yet finished …

The colours are a bit off, true. I mean for one ‘Docs’ should be yellow. That blue-violet colour it has now is like saying that the number 8 is green.
