### ISSUE TITLE
Allow Greek script in team names.

### ISSUE THREAD

**Issue by Debilski** [ASPP/pelita#409]

**Comment by Debilski** [comment]
Currently the check is in pelita/scripts/pelita_player.py anyway, which means that it is basically a client-side check. The main pelita process will try to interpret anything that is sent over json.

We should either fix it in main pelita as well or lift the restriction.

**Comment by Debilski** [comment]
I think this was solved in ac22c8d966fd52a11f85fd241ed5b7f0bceab2f3 .

**Comment by Debilski** [comment]
Ah, no. It still exists.

**Comment by otizonaizit** [comment]
Semi-duplicate of #511
