### ISSUE TITLE
Make it clear how to import a maze to numpy

### ISSUE THREAD

**Issue by Debilski** [ASPP/pelita#434]
Something like

    maze = universe.maze
    np.fromiter(maze.???)

Our `Mapping` representation of the maze does not make it too trivial (involves getting `values` and `reshape`).

**Comment by jni** [comment]
I have an example in my Gordon bot, but I need to revisit it again.

**Comment by Debilski** [comment]
The stable way would be:

    maze_np = np.zeros(maze.width, maze.height)
    for (i, j), v in maze.items():
        maze_np[i, j] = v

(The one-liner `np.fromfunction(tupled(maze.__getitem__), (maze.width, maze.height), dtype=bool)` unfortunately does not work here.)
