### ISSUE TITLE
Player kills enemy while harvester

### ISSUE THREAD

**Issue by Keou0007** [ASPP/pelita#448]
middle of game using call
`pelita --no-timeout --seed 6390651958477911051 team/:team_crf remo:tcp://$IP:30000`

player on left team, moves into enemy_territory and kills defender.

player code at https://github.com/ASPP/group1/tree/Super-Killer-Bug
<img width="895" alt="screen shot 2018-01-20 at 3 24 05 pm" src="https://user-images.githubusercontent.com/14357794/35179826-18c209e8-fdf6-11e7-86b4-676bb6962ae5.png">

**Comment by Debilski** [comment]
UI bug likely introduced in fe08d8f8
