### ISSUE TITLE
`noisy` is `False` by default

### ISSUE THREAD

**Issue by pberkes** [ASPP/pelita#458]
When running a `pelita` game and printing the universe out, I'm getting

```
Team(index=0, zone=(0, 15), score=0)
	Bot(index=0, initial_pos=(1, 13), team_index=0, homezone=(0, 15), current_pos=(1, 13), noisy=False)
	Bot(index=2, initial_pos=(1, 14), team_index=0, homezone=(0, 15), current_pos=(1, 14), noisy=False)
Team(index=1, zone=(16, 31), score=0)
	Bot(index=1, initial_pos=(30, 2), team_index=1, homezone=(16, 31), current_pos=(30, 2), noisy=False)
	Bot(index=3, initial_pos=(30, 1), team_index=1, homezone=(16, 31), current_pos=(30, 1), noisy=False)
```

Which I assume means that noise is turned off by default?

**Comment by pberkes** [comment]
To be clear, I'm just using
`pelita my_team SmartEatingPlayer`
with the template team

**Comment by Debilski** [comment]
Are you printing in my_player or with `--ascii`?

**Comment by Debilski** [comment]
In the latter case, it is expected behaviour because of course the output from the universe will be exact. So it is not a bug, but I agree that it can confuse the user’s expectations. The flag should probably not be shown at all because there is no way it could be true.

**Comment by Debilski** [comment]
Ah, now I understand. It is the printing in `set_initial`. Well, it is correct as you have the exact position of your opponents in that case.

**Comment by pberkes** [comment]
Understood, thanks
