### ISSUE TITLE
Alternative to pdb debugger?

### ISSUE THREAD

**Issue by fmaussion** [ASPP/pelita#468]
Is there a simple way to use the spyder or pycharm debugger instead of pdb?

When running tests with a ``GameMaster`` this is easy of course, but I couldn't find an elegant way to do it for a "real" game. My current approach is to hack ``pelita.scripts.pelita_main.py`` by overwriting the parser arguments with mine a run the pycharm debugger on the hacked main script. 

One solution would be to separate the ``argparse`` logic from the actual game lauch and allow to start a game from python by calling a ``launch_game`` function with reasonable defaults (ideally the same as argparse). Or did I miss something here?

**Comment by Debilski** [comment]
There is a programmatic game launcher function in `pelita.libpelita.call_pelita` (https://github.com/ASPP/pelita/blob/b082a880dec00ff3f8871d779fe406193f198101/pelita/libpelita.py#L187). Unfortunately, the abstraction there is still a bit convoluted as `call_pelita` builds a command line and then basically runs pelita as a subprocess, so I am not sure if it works well with a debugger.
OTOH, in a real game the player code will always be run in a subprocess so if this would not help you at all.

I assume you want to debug a player (or pelita itself)?

You could also try to find a way and run the `pelita_player` code manually (https://github.com/ASPP/pelita/blob/master/pelita/scripts/pelita_player.py – basically `make_client(args).run()`) however this involves quite a bit of additional setup for the viewer and the main game. Maybe I can find a bit of time to write down an example.

It is indeed much simpler if you do not do it in a ‘real’ game but create a `GameMaster` manually – you can still combine this with the Tk viewer though. I’ll provide some examples I think.

**Comment by fmaussion** [comment]
Thanks for the swift reply!

> It is indeed much simpler if you do not do it in a ‘real’ game but create a GameMaster manually – you can still combine this with the Tk viewer though. I’ll provide some examples I think.

Don't spend too much time on this. The solution with the GameMaster is more than enough for now.

I needed (and still need) the debugger for introspection because I'd like to understand in more detail the structure of the game. My feeling is that the students are going to need it too (the doc is great but there is definitely a need for run-time object introspection).

**Comment by fmaussion** [comment]
> having to do introspection with the debugger is one of the reasons we want to do a rewrite away from OO

some of this could be mitigated with a more complete documentation of all methods and attributes available at the AbstractPlayer level (including return types, etc) and maybe with a little less convoluted structure. Ideally, I would like the students to interact with one, max two objects. 

I have yet to get familiar with the codebase to make more concrete suggestions (I haven't yet given up on OO! ;-)

Will the transition away from OO really happen before September?

**Comment by Debilski** [comment]
The basic plan is still to change the API in a way that students won’t have to write the line `class MyPlayer(AbstractPlayer)` again, ie. to primarily get rid of the inheritance model. There *might* still be *objects* for the maze – or not; we haven’t really decided. But the main problem currently is that there are two parallel APIs (`AbstractPlayer` and the `CTFUniverse`) with `AbstractPlayer` only providing convenience accessors (that of course only exist within the class and cannot be tested from outside) and it never being clear where something is defined. Additionally, there is the problem that students might accidentally override methods from `AbstractPlayer` and then get confused why their code fails. (Python’s OO is just not up to today’s standards one has to admit. ;) )
More documentation would be good of course but it would not solve everything.
