### ISSUE TITLE
Consider adding weights to graph.Graph?

### ISSUE THREAD

**Issue by fmaussion** [ASPP/pelita#477]
I don't know if weighted graphs are what you guys are using for your fancy solutions? Maybe I'm on the wrong path here, but this is what I'm exploring right now.

If you do, do you fall back on networkx, or do you have homegrown graphs? The A* search at least should work with weights and little performance loss, I don't know about bfs though.

**Comment by Debilski** [comment]
Yeah, usually, we would expect the students to use more elaborate solutions like networkx than our simple algorithms; those are more for prototyping. We can of course discuss to extend them slightly.

Also, we had an infamous bug in the shortest path calculation for many years that needed the brave efforts of an ASPP student to eventually give us a fix for it. (#371)

**Comment by Debilski** [comment]
Graph has been superseded by directly using networkx in pelita_template. https://github.com/ASPP/pelita_template/pull/21
