### ISSUE TITLE
self.team versus player.current_state

### ISSUE THREAD

**Issue by fmaussion** [ASPP/pelita#478]
It would be nice if the ``self.team`` attr (which points to ``pelita.datamodel.Team``) would also hold other team specific attributes than the score: number of times a bot was killed in the game, number of food pellets the team has eaten.

Currently,  if you want to get this info you have to parse ``self.current_state``, which is clumsy because the dict keys are not exactly self-explanatory and you have to know which side you are.

Thoughts?

**Comment by fmaussion** [comment]
Actually now that I think about it (and correct me if I'm wrong), ``AbstractPlayer.game_state`` shouldn't be there. The info it contains is only partial: all the current_step attributes are empty anyway.

**Comment by Debilski** [comment]
Done in #620
