### ISSUE TITLE
Is there a way to know if a bot was killed last step?

### ISSUE THREAD

**Issue by fmaussion** [ASPP/pelita#479]
(sorry for the spam, and sorry if I missed something)

Currently I can kill a bot in two ways:
- I walk on it (this is predictable and I can take consequences about it)
- It walks on me or my friend-bot (this is unpredictable, but I would like to know when this happens)

Is there a way to parse this information from a player perspective?

[EDIT]: to be more illustrative: if I am bot 4, I'd like to know if bot 3 walked on someone at its step. Currently I am using distance to previous know position for this, but it sounds silly to have to track this yourself.

**Comment by Debilski** [comment]
There is the  `"times_killed"` entry in the `current_state` but it does not tell you about who got killed (this you could find out by checking whether the `current_pos` of the bot has changed to `initial_pos`).

**Comment by Debilski** [comment]
I agree though that a fixup of `current_state` could make this more obvious.

**Comment by fmaussion** [comment]
> this you could find out by checking whether the current_pos of the bot has changed to initial_pos

Yes OK, but ``current_pos`` is noisy in this case, so this comes back to the tracking solution I was talking above right?

**Comment by Debilski** [comment]
Well the noise is not infinite so you could just check whether it is around the home zone. Or you share the information between your two players and then of course you know which bot has moved when you see that the kill count increased.

**Comment by fmaussion** [comment]
Yes yes, I've done all that ;-) I was just wondering if this shouldn't be an in-game attribute.

**Comment by Debilski** [comment]
Maybe. But it’s an educational game after all. :)

**Comment by fmaussion** [comment]
Agreed! I'm already in my "how to make my job as a player-developer easier" mode, which is probably the wrong way to think about the problem here ;)

**Comment by Debilski** [comment]
But don’t let that stop you from opening more issues. There are lots of valid complaints. :)
