### ISSUE TITLE
The new API does not tell the players what their enemies are called

### ISSUE THREAD

**Issue by Debilski** [ASPP/pelita#490]
Is this a wontfix? Or do we want to still pass bits of the `game_state` to the players? Sure we want to keep the new API simple and clean but otoh, those unnecessary pieces of info can be part of the fun.

Also, it breaks @pberkes’s bots. :)

**Comment by otizonaizit** [comment]
We could add a new property to Bot, Bot.team_name. IMHO it is OK to leak this info, and it is part of the fun, so +1.

**Comment by Debilski** [comment]
related: … we also need the timeout count, no? In the next iteration we have to see (with the feedback we get) if we can make the hierarchy slightly less flat.

**Comment by otizonaizit** [comment]
Of these, apart from the enemy team name, which we agreed should be available, I think the number of timeouts it's the only thing you can't guess on your own. I'm not sure what you can do with game_time? Why should you care?

I still think the flat hierarchy is best. It's not like we have hundreds of attributes.

**Comment by Debilski** [comment]
OTOH is knowing about the timeouts actually helpful in any way?

> Am 21.08.2018 um 21:38 schrieb Tiziano Zito <notifications@github.com>:
> 
> Of these, apart from the enemy team name, which we agreed should be available, I think the number of timeouts it's the only thing you can't guess on your own. I'm not sure what you can do with game_time? Why should you care?
> 
> I still think the flat hierarchy is best. It's not like we have hundreds of attributes.
>

**Comment by otizonaizit** [comment]
Sure, for example give up heavy calculations and go for a simpler strategy if you already got several timeouts. Come on, everything which the rules depend on should be available (or easily deducible) from the Bot object. That's the basic principle of the new api.

**Comment by Debilski** [comment]
Closed in #491
