### ISSUE TITLE
`Bot.team` and `Bot.other` are redundant?

### ISSUE THREAD

**Issue by otizonaizit** [ASPP/pelita#504]
I am not sure if we discussed about it, but in the new API the Bot object holds a reference to
the other bot (`Bot.other`) and to the team (`Bot.team`). Given that both these things are actually already avaiable as `game.team` and `game.team[1-turn]` we can get rid of them? If they are needed internally then they should be prefixed with a `_`. All other public attributes and methods of `Bot` make sense and can be presented to the students. Removing them is not going against the principle of the flat API we decided for, so I think they can go.

**Comment by Debilski** [comment]
They shouldn’t be needed internally, no (at least we would be able to recreate them). On the other hand though, if your aim is also to get rid of the internal references, it might make a bit of sense to also add `enemy` to `Game` and remove it from `Bot`.
I’m undecided though. I see no harm in having those shortcuts. Better than having to type `turn - 1` anyway.

**Comment by otizonaizit** [comment]
Well, they are somehow needed in Team, because a simple patch that removes them from Bot doesn't work. Second, the discussion about enemy in `Game` or in `Bot` is a different one, so for now let first remove `team`, and `other`. Right now people have to type:
````
bot = game.team[turn]
```
in any case, so if they need other, they will add a line with

```
other = game.team[1-turn]
```

and `Bot.team` is completely redudant.
Get rid of the two. If they are needed internally, prefix them with `_` and we are done.

Again, you can open another issue with `enemy` but I don't think it is worth it. Otherwise we start the discussion again if `round` belongs to `Game` or `Bot`, etc. With this I just want to remove redundancy, not restructuring the hierarchy.
