### ISSUE TITLE
Can we add (0, 0) a.k.a stop to Bot.legal_moves?

### ISSUE THREAD

**Issue by otizonaizit** [ASPP/pelita#505]
I am not sure why this is excluded, but it seems an oversight. Stopping is always a legal move, so why shouldn't it be on the list? This will make some special casing in the code not needed anymore...

**Comment by Debilski** [comment]
You will have to special-case other things then. :)

**Comment by otizonaizit** [comment]
Not really. Or at least, not in user-facing code right now.

**Comment by Debilski** [comment]
Depends. :) But yeah, +1 for adding.
