### ISSUE TITLE
Detecting unicode team names fails and returns wrong Exception

### ISSUE THREAD

**Issue by otizonaizit** [ASPP/pelita#513]
While checking how to enforce ascii for the `.say` method (related to #511 ), I stumbled upon this:
```
$ mkdir /tmp/team1 /tmp/team2
$ cat > /tmp/team1/__init__.py <<EOF
from pelita.player import SimpleTeam, StoppingPlayer
def team():
    return SimpleTeam("∂", StoppingPlayer, StoppingPlayer)
EOF
$ cat > /tmp/team2/__init__.py <<EOF
from pelita.player import SimpleTeam, StoppingPlayer
def team():
    return SimpleTeam("d", StoppingPlayer, StoppingPlayer)
EOF
$ pelita /tmp/team1 /tmp/team2
...
Replay this game with --seed 9137218428567681684
Using layout 'layout_normal_without_dead_ends_017'
Red team '/tmp/team2' -> 'd'
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/tiziano/git/pelita/pelita/scripts/pelita_player.py", line 266, in <module>
    main()
  File "/home/tiziano/git/pelita/pelita/scripts/pelita_player.py", line 260, in main
    client = make_client(args.team, args.address, args.color)
  File "/home/tiziano/git/pelita/pelita/scripts/pelita_player.py", line 42, in make_client
    team = load_team(team_spec)
  File "/home/tiziano/git/pelita/pelita/scripts/pelita_player.py", line 108, in load_team
    check_team_name(team.team_name)
  File "/home/tiziano/git/pelita/pelita/scripts/pelita_player.py", line 65, in check_team_name
    name.encode('ascii')
UnicodeEncodeError: 'ascii' codec can't encode character '\u2202' in position 0: ordinal not in range(128)
```

This is wrong, because this code is supposed to raise `ValueError` when the team name contains non-ascii characters, see https://github.com/ASPP/pelita/blob/5916947cb8cbc3cfb087d65509d6f3e507b36176/pelita/scripts/pelita_player.py#L67 .
The problem with that line is that it is catching `UnicodeDecodeError` while it should be catching `UnicodeEncodeError`. I wanted to fix that and add a test, and then realized that there is a test already: https://github.com/ASPP/pelita/blob/5916947cb8cbc3cfb087d65509d6f3e507b36176/test/test_pelita_player.py#L78
I do not understand how it is possible for that test to pass, because if, like above, I replicate the setup manually and run the script from the commandline, I indeed get the wrong exception, i.e. `UnicodeEncodeError` instead of `ValueError`. @Debilski : any clue why the test is passing and how to make it fail so that I can test my fix?

**Comment by otizonaizit** [comment]
Why has this be closed? This line here: https://github.com/ASPP/pelita/blob/5916947cb8cbc3cfb087d65509d6f3e507b36176/pelita/scripts/pelita_player.py#L66 should be catching `UnicodeEncodeError`.

**Comment by Debilski** [comment]
Here is the fix: https://github.com/ASPP/pelita/commit/aa179ac188dc89d8defa82179e96d5f7afec3f4f
