### ISSUE TITLE
Bot.is_noisy is always False when created from a layout

### ISSUE THREAD

**Issue by otizonaizit** [ASPP/pelita#514]
This line:
https://github.com/ASPP/pelita/blob/b0899449d58b49aec3123a324fd7c49fe0641684/pelita/player/team.py#L436
sets the `.is_noisy` property to `False` for all the bots created from a layout string, indipendent of their respective distances. This makes testing quite harder, because you can't rely on that property.
This should be fixed, probably together with the efforts in recreating a complete universe when `setup_test_game` is run...

**Comment by Debilski** [comment]
Hmm. That’s indeed a difficult problem. is_noisy is dependent on whose turn it is, whereas setup_test_game is not. Not sure how we would want to solve it.

**Comment by otizonaizit** [comment]
>Hmm. That’s indeed a difficult problem. is_noisy is dependent on whose turn it is, whereas setup_test_game is not. Not sure how we would want to solve it.

add a turn option to setup_test_game, so that you can explicitly choose whose bot turn it is...

**Comment by otizonaizit** [comment]
>>Hmm. That’s indeed a difficult problem. is_noisy is dependent on whose turn it is, whereas setup_test_game is not. Not sure how we would want to solve it.
>
>add a turn option to setup_test_game, so that you can explicitly choose whose bot turn it is...
>
Also, do I understand correctly that, if turn==0, but game.team[1] is nearer than 5 squares from game.team[0].enemy[0], then we currently have that:

game.team[0].enemy[0].is_noisy == True , and
game.team[1].enemy[0].is_noisy == False ?

That is what I would expect looking at the UniverseNoiser code, but I'd like this to be confirmed by a human :)

**Comment by Debilski** [comment]
> Am 30.08.2018 um 14:09 schrieb Tiziano Zito <notifications@github.com>:
> 
> >Hmm. That’s indeed a difficult problem. is_noisy is dependent on whose turn it is, whereas setup_test_game is not. Not sure how we would want to solve it.
> 
> add a turn option to setup_test_game, so that you can explicitly choose whose bot turn it is...

Will it raise an exception then, if you run move on a game with the wrong turn specified?

**Comment by Debilski** [comment]
> Am 30.08.2018 um 14:11 schrieb Tiziano Zito <notifications@github.com>:
> 
> >>Hmm. That’s indeed a difficult problem. is_noisy is dependent on whose turn it is, whereas setup_test_game is not. Not sure how we would want to solve it.
> >
> >add a turn option to setup_test_game, so that you can explicitly choose whose bot turn it is...
> >
> Also, do I understand correctly that, if turn==0, but game.team[1] is nearer than 5 squares from game.team[0].enemy[0], then we currently have that:
> 
> game.team[0].enemy[0].is_noisy == True , and
> game.team[1].enemy[0].is_noisy == False ?
> 
> That is what I would expect looking at the UniverseNoiser code, but I'd like this to be confirmed by a human :)

Yes. You only see the world as your current Bot sees it. There is no instant communication so to speak.

I think we also never really clarified this before. In only started to learn it myself with the new Game print. :)

**Comment by otizonaizit** [comment]
On Thu 30 Aug, 05:43 -0700, Rike-Benjamin Schuppner <notifications@github.com> wrote:
>> Am 30.08.2018 um 14:11 schrieb Tiziano Zito <notifications@github.com>:
>>
>> >>Hmm. That’s indeed a difficult problem. is_noisy is dependent on whose turn it is, whereas setup_test_game is not. Not sure how we would want to solve it.
>> >
>> >add a turn option to setup_test_game, so that you can explicitly choose whose bot turn it is...
>> >
>> Also, do I understand correctly that, if turn==0, but game.team[1] is nearer than 5 squares from game.team[0].enemy[0], then we currently have that:
>>
>> game.team[0].enemy[0].is_noisy == True , and
>> game.team[1].enemy[0].is_noisy == False ?
>>
>> That is what I would expect looking at the UniverseNoiser code, but I'd like this to be confirmed by a human :)
>
>Yes. You only see the world as your current Bot sees it. There is no instant communication so to speak.
>
>I think we also never really clarified this before. In only started to learn it myself with the new Game print. :)
>
Well no, if the above example works, you *do* see the world as your team mate sees it, i.e. you see the non noisy position. To be clear, I think this is the correct thing to do, I wanted to be sure that this is the case. I tried to write a test for this behavior using the new API, and failed because of this very #514 issue.

**Comment by otizonaizit** [comment]
On Thu 30 Aug, 05:41 -0700, Rike-Benjamin Schuppner <notifications@github.com> wrote:
>
>
>> Am 30.08.2018 um 14:09 schrieb Tiziano Zito <notifications@github.com>:
>>
>> >Hmm. That’s indeed a difficult problem. is_noisy is dependent on whose turn it is, whereas setup_test_game is not. Not sure how we would want to solve it.
>>
>> add a turn option to setup_test_game, so that you can explicitly choose whose bot turn it is...
>
>Will it raise an exception then, if you run move on a game with the wrong turn specified?
>
No, why? Who would raise the Exception? setup_test_game returns a game in certain defined state. You call your move function on that state, but the turn is (for good reasons) a different argument to the function. You can of course create the game a turn==0 and then run move with turn==1, but that is your problem. There's no one here that could raise an Exception.

**Comment by Debilski** [comment]
> On 30. Aug 2018, at 14:58, Tiziano Zito <notifications@github.com> wrote:
> 
> On Thu 30 Aug, 05:41 -0700, Rike-Benjamin Schuppner <notifications@github.com> wrote:
>> 
>> 
>>> Am 30.08.2018 um 14:09 schrieb Tiziano Zito <notifications@github.com>:
>>> 
>>>> Hmm. That’s indeed a difficult problem. is_noisy is dependent on whose turn it is, whereas setup_test_game is not. Not sure how we would want to solve it.
>>> 
>>> add a turn option to setup_test_game, so that you can explicitly choose whose bot turn it is...
>> 
>> Will it raise an exception then, if you run move on a game with the wrong turn specified?
>> 
> No, why? Who would raise the Exception? setup_test_game returns a game in certain defined state. You call your move function on that state, but the turn is (for good reasons) a different argument to the function. You can of course create the game a turn==0 and then run move with turn==1, but that is your problem. There's no one here that could raise an Exception.

Depends. Currently no, there is no reason to raise. But I see it forthcoming that Game will gain more complexity and rely on the turn (if only to include state info of proper scoring and who has won). But that’s not an argument that we should have now. :)

**Comment by otizonaizit** [comment]
So, you think you can fix setup_test_game? (before ASPP-2018)?

**Comment by Debilski** [comment]
> On 30. Aug 2018, at 14:56, Tiziano Zito <notifications@github.com> wrote:
> 
> On Thu 30 Aug, 05:43 -0700, Rike-Benjamin Schuppner <notifications@github.com> wrote:
>>> Am 30.08.2018 um 14:11 schrieb Tiziano Zito <notifications@github.com>:
>>> 
>>>>> Hmm. That’s indeed a difficult problem. is_noisy is dependent on whose turn it is, whereas setup_test_game is not. Not sure how we would want to solve it.
>>>> 
>>>> add a turn option to setup_test_game, so that you can explicitly choose whose bot turn it is...
>>>> 
>>> Also, do I understand correctly that, if turn==0, but game.team[1] is nearer than 5 squares from game.team[0].enemy[0], then we currently have that:
>>> 
>>> game.team[0].enemy[0].is_noisy == True , and
>>> game.team[1].enemy[0].is_noisy == False ?
>>> 
>>> That is what I would expect looking at the UniverseNoiser code, but I'd like this to be confirmed by a human :)
>> 
>> Yes. You only see the world as your current Bot sees it. There is no instant communication so to speak.
>> 
>> I think we also never really clarified this before. In only started to learn it myself with the new Game print. :)
>> 
> Well no, if the above example works, you *do* see the world as your team mate sees it, i.e. you see the non noisy position. To be clear, I think this is the correct thing to do, I wanted to be sure that this is the case. I tried to write a test for this behavior using the new API, and failed because of this very #514 issue.

Wait, now that I read it correctly: Why are you checking `game.team[0].enemy[0]` and `game.team[1].enemy[0]`? That does not make much sense, no? There is no clear definition anywhere which enemies you’ll get then. They could be the same or they could be different. You want `bot.enemy[0]` and `bot.enemy[1]` (and `bot` could be `game.team[0]` or `game.team[1]` it does not matter.

**Comment by Debilski** [comment]
Mails got stuck in the outgoing queue … I’ll see what I can do.

**Comment by otizonaizit** [comment]
On Thu 30 Aug, 16:31 +0000, Rike-Benjamin Schuppner <notifications@github.com> wrote:
>Wait, now that I read it correctly: Why are you checking `game.team[0].enemy[0]` and `game.team[1].enemy[0]`? That does not make much sense, no? There is no clear definition anywhere which enemies you’ll get then. They could be the same or they could be different. You want `bot.enemy[0]` and `bot.enemy[1]` (and `bot` could be `game.team[0]` or `game.team[1]` it does not matter.

I check `game.team[0].enemy[0]` and `game.team[1].enemy[0]` because it is possible right now and gives one bot with a noisy position and one without (if one of the two bots in my team is near enough). That's the whole point of this discussion. It is perfectly defined who the two enemy bots are, no? They are, like my bots, identified by their turn index. And they are almost identical, they can only differ by their position iff they are noisy. So, if I am clever I can use this to my advantage. Just, I wanted to write a test to verify that it really is like this, but couldn't.

**Comment by Debilski** [comment]
But that’s not possible. Game only contains 4 bots in total. There are no bots generated for the other team. In fact `id(game.team[0].enemy[0]) == id(game.team[1].enemy[0])` (but that’s an implementation detail; the indexes for the enemy could as well differ).

**Comment by otizonaizit** [comment]
OK, if the `id` is the same, I can live with that. So, if I am clever, in the previous turn I can store the position of my enemies if they are not noisy, and pass them over to th eother bot, so that he can have a better estimate of their position (they will be at most at distance 1 from their previous position).

**Comment by otizonaizit** [comment]
We now only need a way to set `is_noisy` correctly in `setup_test_game`

**Comment by Debilski** [comment]
Yes and yes.

**Comment by otizonaizit** [comment]
OK, so you can fix `setup_test_game` before Sunday? That would be cool.

**Comment by Debilski** [comment]
The time is sufficient (but read on). But after thinking about it some more: Unless we give the actual positions in the maze (and then apply our noising algorithm) there is no way to infer (in general) wether a bot is noisy or not. (One could see it as a direct neighbour but in fact it could be 5 steps further than that.)
Was the idea to setup a game with correct positions to fake what a user would be seeing? In the second case one would have to supply the information manually about which bot is noised. (Which we actually cannot do because we don’t enumerate the enemies. Hence there is no way to tell from the layout which enemy gets which (internal) id. The only way would be to generate a game and then go through the enemies and explicitly set up which is noised and which isn’t.)

Any idea?

**Comment by otizonaizit** [comment]
Yes, I understand now. Ok, so the solution for the test is to manually set the is_noisy property on the respective enemy bot *before* calling 'move' on the game instance. Maybe all these properties on Bot should get setter methods, so that we can use them in the tests.
Should you do that instead?

**Comment by Debilski** [comment]
We could make is_noisy simply a plain variable as well, right?

> Am 30.08.2018 um 20:41 schrieb Tiziano Zito <notifications@github.com>:
> 
> Yes, I understand now. Ok, so the solution for the test is to manually set the is_noisy property on the respective enemy bot *before* calling 'move' on the game instance. Maybe all these properties on Bot should get setter methods, so that we can use them in the tests.
> Should you do that instead?
> 
>

**Comment by otizonaizit** [comment]
yes. that is true for all properties, I think. The fact that you can better document properties than attributes is not so relevant IMHO, given that we do not suggest students to look into Pelita's code. So, all properties could go and be replaced by attributes.

**Comment by Debilski** [comment]
Then the job is already done btw. :)
