### ISSUE TITLE
change new client API. From move(turn, game) to move(turn, game, state)

### ISSUE THREAD

**Issue by otizonaizit** [ASPP/pelita#520]
After the first run of the API on students it seems clear that having the state stored in the attribute `game.state` was a bad idea. We should move it to an additional argument to the `move` function, `None` by default. The `move` function should then return `next_move, state`. 

After this is done, it is just a matter of updating the documentation on `pelita_template` and update the demos. Not a lot of work.

**Comment by Debilski** [comment]
While I agree that it is somehow the right thing to do, it feels a little unpythonic (in the sense that people are not really used to doing things that way) to me to require returning a tuple. Do we have any alternative ideas?

Also, for the record, the `Game` object will still have to be writeable, as it keeps the rng and the say variable. I assume this should stay that way, right?

**Comment by otizonaizit** [comment]
> While I agree that it is somehow the right thing to do, it feels a little unpythonic (in the sense that people are not really used to doing things that way) to me to require returning a tuple. Do we have any alternative ideas?

No, short of mandating a global variable `STATE`, I don't see any better way. On top of that, I don't see the problem with returning a tuple. Why would it be unpythonic? What does that mean?
As usual, documentation makes all of the difference. If we use the new `state` argument consistently in the demos and document it properly in the template repo, it is going to create exactly zero problems.

> Also, for the record, the `Game` object will still have to be writeable, as it keeps the rng and the say variable. I assume this should stay that way, right?

Of course, there is no way to have a read-only object for real in Python anyway. But, from the point of view of the user, `Game` is going to be read-only now (`rng` is initiliazed before the user can interact with `Game`, and `say` is a method on `Bot`, so there's no reason for the user to assume that it is going to set some special attribute in `Game`). Again, I don't care much about the internals, I care about a consistent API for the end user.

**Comment by Debilski** [comment]
> Am 19.09.2018 um 14:55 schrieb Tiziano Zito <notifications@github.com>:
> 
> While I agree that it is somehow the right thing to do, it feels a little unpythonic (in the sense that people are not really used to doing things that way) to me to require returning a tuple. Do we have any alternative ideas?
> 
> No, short of mandating a global variable STATE,
> 

Well, that would be even worse than what we have now.

> I don't see any better way. On top of that, I don't see the problem with returning a tuple. Why would it be unpythonic? What does that mean?
> 
My point is that people are not really used to have functions that return two arguments and it might lead to different problems, even if we document it well. I am all for trying it though, because it does make sense and I don’t see another good way either.

> As usual, documentation makes all of the difference. If we use the new state argument consistently in the demos and document it properly in the template repo, it is going to create exactly zero problems.
> 
> Also, for the record, the Game object will still have to be writeable, as it keeps the rng and the say variable. I assume this should stay that way, right?
> 
> Of course, there is no way to have a read-only object for real in Python anyway. But, from the point of view of the user, Game is going to be read-only now (rng is initiliazed before the user can interact with Game, and say is a method on Bot, so there's no reason for the user to assume that it is going to set some special attribute in Game). Again, I don't care much about the internals, I care about a consistent API for the end user.
>

**Comment by Debilski** [comment]
Has been implemented.
