### ISSUE TITLE
new API: enemy bots should only have properties that are updated! 

### ISSUE THREAD

**Issue by otizonaizit** [ASPP/pelita#522]
In the new API there is right now a bit of a confusion around the enemy bots objects. Are their properties updated? For example,  is `game.team[0].eneme[0].legal_moves` really returning the legal moves of the enemy bot for this turn? And if yes, is this taking into account the noise? If not, then the property shouldn't be there.

We should review all the enemy bot properties and remove all that are not updated or do not make sense.

**Comment by Debilski** [comment]
After looking at it, I think `legal_moves` is the one that makes sense actually even on the enemy bots. You could manually reset the position of the bot and will update the `legal_moves` (maybe it should become an explicit function then?).

If we remove `game.state` though, will we still have `game.team` as the only property on `Game` or should we rather split it up into `game.team[]`, `game.enemy[]`, `game.walls` …

**Comment by otizonaizit** [comment]
legal_moves only makes sense if the enemy position is not noisy. So I think it's cleaner to just remove it. In case you need it when the enemies are near, it is easy enough to code it yourself.

Regarding splitting up game: no. The deeply nested hierarchies were cause for much confusion in the old API. Otherwise we will start again arguing about, for example, score: should it be a property of team? Or of bot? And what about food? And, and, and...

 It's not a matter of esthetics, it's a matter of practicality: we didn't get a single question about where properties were to be found. This is because everything was under bot. Removing game.state makes even cleaner in my opinion.

**Comment by Debilski** [comment]
Should `legal_positions` still be removed, @otizonaizit ?

**Comment by otizonaizit** [comment]
Not sure anymore we really need to remove it. Is it updated correctly? In the sense that it gives you the legal position if the both were in the noisy position? If yes, I think it can stay. If not, in the sense that legal_positions returns bullshit, then it should be removed. I have no time right now to look in to the code: can you have a look at it?

**Comment by Debilski** [comment]
It is a property and returns depending on what is set as Bot.position.

**Comment by otizonaizit** [comment]
so it's updated based on the "perceived" position of the enemy by the bot, right? Then it can stay, I'd say.

**Comment by Debilski** [comment]
> so it's updated based on the "perceived" position of the enemy by the bot, right?

Well, of course.
