### ISSUE TITLE
bot.track should be writable

### ISSUE THREAD

**Issue by otizonaizit** [ASPP/pelita#537]
In general `bot.track` should not be written to. But it is useful in tests. For now, for example, to make this test work: https://github.com/ASPP/pelita_template/blob/1d7ebe9fd38b7c59a7b2b7b4ffda7428d7f4efd1/test_demo04_basic_attacker.py#L27 we would need to use `bot._track`, which is not documented anywhere. I think there's no danger in making `bot.track` writable.

**Comment by Debilski** [comment]
Sounds good. But then we should copy a new track to `Bot` every time we create the bots (probably would have been a good idea anyway).
