### ISSUE TITLE
pelita only loading team.team, not team.<any other name>

### ISSUE THREAD

**Issue by jennirinker** [ASPP/pelita#547]
Probably related to old API.

I have a team/ directory with an `__init__` file containing several different teams composed of different players using the old API. E.g., `def team1():` and `def team2()`.

I want to play two of these teams against each other: `$ pelita team.team1 team.team2`.

But by default it only pulls `team.team`.

**Comment by Debilski** [comment]
`pelita team:team1 team:team2`

**Comment by jennirinker** [comment]
I knew I was doing something wrong. Closing.
