### ISSUE TITLE
Consider (again) swapping the axes in Pelita coordinate system

### ISSUE THREAD

**Issue by jni** [ASPP/pelita#549]
I have at least one team that was confused about the legal moves being illegal, because the axes are not the same as in NumPy.

**Comment by otizonaizit** [comment]
We are still wondering what the point is. Just imagine what happens in the viewer when you pinpoint a grid cell and the coordinates shown there are swapped (y would be horizontal and x vertical)...
What exactly would be the usefulness of swapping again?
