### ISSUE TITLE
rename Bot.has_respawned

### ISSUE THREAD

**Issue by otizonaizit** [ASPP/pelita#589]
What about renaming `Bot.has_respawned` to `Bot.was_killed`? The word _respawned_ is totally meaningless for most non-hardcore programmers.

**Comment by Debilski** [comment]
I fail to see the connection to hardcore programmers (it is more of a gamer’s thing, no?) here but I’m open for any wording changes that make the intention clearer (not only this one).

**Comment by otizonaizit** [comment]
Yep, _gamers_ is more correct. Anyway, the point stands. Do you agree with `was_killed`? Does the attribute counts the killings or is just `True` at the next turn after the `Bot` has been killed?

**Comment by Debilski** [comment]
In the backend we have `times_killed`, which counts the total number times that a *team* has been killed (but which is currently not exposed to the Bot but that wouldn’t be a problem to do – teams can easily implement it themselves though). The `was_killed` flag would be per Bot and is boolean.

**Comment by Debilski** [comment]
Correction: We currently have `deaths` and `times_killed` in the backend but I think only `deaths` is used. I think I added `times_killed` not knowing that we already had the other attribute. I am open to switch to either one of them.

**Comment by Debilski** [comment]
@otizonaizit since we recently changed the flag to `Bot.eaten` and this issue is still open. Should it still become `Bot.was_killed`? (This would reserve *eaten* only for food.)

**Comment by Debilski** [comment]
If we rename it to `Bot.was_killed`, it makes some sense to change `Bot.deaths` to `Bot.times_killed` as well. (`Bot.kills` could become `Bot.num_kills` which reduces a bit of the ambiguity, I’d say.)

**Comment by otizonaizit** [comment]
I can be convinced about was_killed, surely not for changing "deaths" nor "kills": if you read the docs in pelita_template there's no ambiguity. I'm ready to bet that we won't get questions about these names at the school.
I agree that "eaten" is ambiguous, because the terminology we adopted is that you "eat" food and "kill" bots.

**Comment by Debilski** [comment]
I don’t want to convince you for `was_killed`. It was your idea all along. :)

**Comment by otizonaizit** [comment]
So, if you have time, go for was_killed. Also in pelita_template.
