### ISSUE TITLE
--timeout setting is ignored in RemoteTeam

### ISSUE THREAD

**Issue by Debilski** [ASPP/pelita#598]
We need to add (or rather: reenable) proper handling of timeouts in RemoteTeam. Also, each timeout now creates two errors. The timeout itself and an illegal move error.

**Comment by Debilski** [comment]
@otizonaizit have you already started to work on this? Otherwise I’ll assign it to myself (+ RemoteTeam refactoring)

**Comment by otizonaizit** [comment]
No, I am not. I found the problem while working on pelita_template refactoring.

**Comment by Debilski** [comment]
@lschwetlick Not sure there is super much to do for `RemoteTeam`, actually. I won’t introduce any big API breaking changes there, just make the timeout and error handling a little clearer. But it should be finished today hopefully.

**Comment by otizonaizit** [comment]
Regarding the refactoring, it would be good then to remove _all_ of the remaining relics of CTFuniverse, datamodel, etc. For the sprint in summer we would like to have a state where all the code in pelita is used and nothing is there for historical reasons (for example, the load_factory stuff).

**Comment by Debilski** [comment]
Tbh, I think `load_factory` is actually the only function left that is currently not used. (Of course, the simplesetup stuff needs more refactoring/repackaging, but most of the old API *is* already gone.)

**Comment by otizonaizit** [comment]
well, "most" of the old API is not "all" of the old API. Yesterday we were struggling our way between SimpleTeam, AbstractTeam, etc... That stuff must go, no?

**Comment by lschwetlick** [comment]
> @lschwetlick Not sure there is super much to do for `RemoteTeam`, actually. I won’t introduce any big API breaking changes there, just make the timeout and error handling a little clearer. But it should be finished today hopefully.

The problem is that we were having some trouble understanding some of the Team code. Some of it felt quite convoluted. Maybe part of what needs doing is also documenting more how it works then.

**Comment by Debilski** [comment]
Ah, sorry, forgot about `SimpleTeam`/`AbstractPlayer`. Yeah, this is unused but still in there for reference, if someone wants to write a new object oriented API or rewrite their old player. I guess we should move it somewhere else.

**Comment by Debilski** [comment]
Found a nasty bug in the messages layer. This will need a little more polishing than initially thought.
