### ISSUE TITLE
remove demo

### ISSUE THREAD

**Issue by otizonaizit** [ASPP/pelita#623]
remove demo/demo04_basic_attacker.py and put it somewhere else

**Comment by Debilski** [comment]
Why did you remove the statistics demo?

**Comment by otizonaizit** [comment]
>Why did you remove the statistics demo?
>

Because it's in pelita_template already.

**Comment by Debilski** [comment]
> On 14. Aug 2019, at 16:35, Tiziano Zito <notifications@github.com> wrote:
> 
> >Why did you remove the statistics demo?
> >
> 
> Because it's in pelita_template already.

Ah. That makes sense. :)
