### ISSUE TITLE
Add traffic light to Tk viewer to show whose turn it is

### ISSUE THREAD

**Issue by Debilski** [ASPP/pelita#624]
Something in the spirit of

![](https://user-images.githubusercontent.com/216179/61712965-c592c100-ad57-11e9-937b-db6b9b3ed2b3.gif)

A more advanced design could even do a radial wipe animation inside the full circle for the three second count down. :)

**Comment by Debilski** [comment]
Demo video … https://vimeo.com/349846095

**Comment by otizonaizit** [comment]
if the code is not too terrible, make a PR of this! it's not bad at all.

**Comment by otizonaizit** [comment]
when the grid is on this should have the bot_idx on top, or right below the corresponding lamp.

**Comment by Debilski** [comment]
I think it should be a little smaller, I find it still too irritating. But then the lack of anti-aliasing kicks in and it looks pretty bad again …

**Comment by otizonaizit** [comment]
It's good enough. PR!
