### ISSUE TITLE
too much clutter in TK-UI header and overlapping letters on high-res display

### ISSUE THREAD

**Issue by otizonaizit** [ASPP/pelita#625]
I tried and failed to add a bit more padding around the strings in the headers of the TK-UI. On my desktop with a high-res display, the text looks cluttered and some fonts are overlapping. Of course TK is the problem here, but I think more padding is better then no padding, even if it looks a bit sparse on normal displays. Screenshot attached.
![screenshot1](https://user-images.githubusercontent.com/347147/61714671-b7df3a80-ad5b-11e9-8d6f-3e25ba3bb90e.png)

**Comment by Debilski** [comment]
Did you test against conda/non-conda versions of Tk also? I noticed that conda interpretes the padding values very differently anyway.

**Comment by otizonaizit** [comment]
using non conda tk here, just plain Debian installation.

**Comment by Debilski** [comment]
I honestly think Tk is unfixable :(

**Comment by Debilski** [comment]
I think we should remove the lines around the canvas (did so in the latest commit for the traffic lights). This will already help a little with decluttering. (Not sure, why we never fixed this before)
