### ISSUE TITLE
Don’t filter the layout with strings but with tags

### ISSUE THREAD

**Issue by Debilski** [ASPP/pelita#629]
Right now, if we want to select a random, small layout that has no dead ends, we have to run

    layout_name, layout_string = get_random_layout(filter='small_with_dead_ends')

and we could even add the layout number to that string `'small_with_dead_ends_001'`, which doesn’t even make sense for a random layout.

I think a better way to select layouts would be:

    layout_name, layout_string = get_random_layout(filter=['small', 'dead_ends'])

Or even:

    layout_name, layout_string = get_random_layout(size='small', style='dead_ends')

**Comment by otizonaizit** [comment]
Fixed by #661
