### ISSUE TITLE
Running Pelita logs me out of macOS 10.14.6

### ISSUE THREAD

**Issue by Debilski** [ASPP/pelita#631]
Seems to only happen with Tk. I already noticed it with the recent macOS 10.15 beta on a different computer (video on Twitter below) but now it appears to be happening on the newest regular macOS 10.14.6 …

To reproduce: Type `pelita` on the command line → get logged off.

Pretty sure it is not ‘our’ fault but we should maybe figure out how people can solve it.

Video: https://twitter.com/debilski/status/1153295394266333185

**Comment by Debilski** [comment]
Leaving the issue open until it is fixed in macOS 10.14 (the newest beta seems to have fixed it somehow).
A workaround seems to be to downgrade tk: `conda install tk=8.6.7`. This also downgrades Python to 3.7.0, however.

**Comment by lschwetlick** [comment]
This doesnt happen on my MacOS 10.14.6.

**Comment by Debilski** [comment]
> This doesnt happen on my MacOS 10.14.6.

What is your version of tk and Python?

**Comment by lschwetlick** [comment]
Python 3.6.3, tkinter.TKversion is 8.5.

**Comment by Debilski** [comment]
Only happens with tk=8.6.8 for me

**Comment by Debilski** [comment]
Someone reported to Anaconda https://github.com/ContinuumIO/anaconda-issues/issues/11165 , I gave feedback to Apple.

**Comment by otizonaizit** [comment]
What's the status on this?

**Comment by Debilski** [comment]
It is still bad

**Comment by Debilski** [comment]
Fixed on macOS Catalina but probably still broken on older macOS.

**Comment by Debilski** [comment]
Cannot do much about this. Closing. For the record: If you have macOS mojave and tk 8.6.8 (`conda list` will tell you), you must upgrade one or the other or Pelita will be unusable.
