### ISSUE TITLE
Add width and height to the layout dictionary

### ISSUE THREAD

**Issue by otizonaizit** [ASPP/pelita#673]
As it is needed in several places, it makes sense to just stick two additional keys into the layout dictionary. Fixing this bug also means getting rid of all `max(walls)[0]+1`, `max(walls)[1]+1`, `sorted(walls)[-1][0]`, `sorted(walls)[-1][1]` spread in the pelita and pelita_template code.

**Comment by Debilski** [comment]
Plus the walls (and food) should be made a set. Both of it slow down `get_legal_positions` considerably which in turn is where `apply_move` spends most of its time (and thus makes move simulations very slow).
