### ISSUE TITLE
setup_viewers shouldn't add ResultPrinter unconditionally to the list of viewers

### ISSUE THREAD

**Issue by otizonaizit** [ASPP/pelita#679]
Here https://github.com/ASPP/pelita/blob/6146c1db6142cedecf4ed0be21069d59a7036115/pelita/game.py#L159
The ResultPrinter viewer is added unconditionally to the list of viewers. It shouldn't. If the list of viewers is empty, then nothing should be printed. The problem appears when trying to run background games with `run_background_game`: the final result is printed. If running a lot of games this is annoying.
Not sure if this can be simply added only when `viewers is not None`, because it is not clear to me if the tournament code needs this.

**Comment by Debilski** [comment]
What about all the uses of `game_print`? Maybe it is better to add a `silent_mode` flag to `setup_game` that also takes care of silencing these and also make the intention clearer (`run_background_game` would just set this flag of course not expose it)? The tournament doesn’t need the `ResultPrinter`, but it should have it activated so we can follow what is happening on the command line, too.

I don’t actually think this will be much of an additional annoyance for the students though, as 80% will have dozens of `print`s in their own code, so I wouldn’t consider it too urgent.

**Comment by otizonaizit** [comment]
On Fri 16 Aug, 03:36 -0700, Rike-Benjamin Schuppner <notifications@github.com> wrote:
>What about all the uses of `game_print`? Maybe it is better to add a `silent_mode` flag to `setup_game` that also takes care of silencing these and also make the intention clearer (`run_background_game` would just set this flag of course not expose it)? The tournament doesn’t need the `ResultPrinter`, but it should have it activated so we can follow what is happening on the command line, too.
>
>I don’t actually think this will be much of an additional annoyance for the students though, as 80% will have dozens of `print`s in their own code, so I wouldn’t consider it too urgent.
>

It is not too urgent, I agree. But if it can be fixed before ASPP-2019 it is better.
