### ISSUE TITLE
layout_agnostic needs tests and fixes

### ISSUE THREAD

**Issue by Debilski** [ASPP/pelita#695]
Currently broken. https://github.com/ASPP/pelita/blob/2f17db5355b4dffae8a130ede549ab869b2f1ce2/pelita/layout.py#L548-L566

**Comment by DanBenHa** [comment]
Can I work on this? I'm PR hunting for Hacktoberfest 😄

**Comment by Debilski** [comment]
Go for it. I’ll try to find some more easy issues and add them over the next days.
