### ISSUE TITLE
bot.homezone and bot.walls are sets, bot.food is a list

### ISSUE THREAD

**Issue by otizonaizit** [ASPP/pelita#760]
sets have the problem of having a non-deterministic order, so that if the code depends on the order the games are not replicable.

I think that for this kind of things we should always return list of coordinates. I think we used sets for efficiency reasons, but I think easiness of use and students' expectations are more important in this case.

**Comment by Debilski** [comment]
The efficiency discussion was done in #708 . Food was kept as a list in order to keep random.choice working.

**Comment by Debilski** [comment]
Merged in #767
