### ISSUE TITLE
Add new `Bot.graph` attribute

### ISSUE THREAD

**Issue by otizonaizit** [ASPP/pelita#789]
After several years of experience with the new `Bot` API it is clear that almost all players sooner or later use the `pelita.utils.walls_to_graph` function to generate a graph representation of the maze.

In the demo bots we show how to store this into `state`.

Inexperienced programmers tend to overlook the fact that it is expensive to create the graph, and prefer to just do it at every turn instead of trying to understand how to use `state`.

My suggestion is to just bite the bullet and make `Bot.graph` a default attribute for the `Bot` object. It can be created once at the beginning of the game and cached.

This will remove the need of using `state` for something which is actually not different than `bot.walls` in terms of use.

**Comment by otizonaizit** [comment]
Well, we can protect all attributes by making them read-only properties. So they will get an error when they try to do anything with it. Or, for `graph`, we can just use this: https://networkx.org/documentation/stable/reference/generated/networkx.classes.function.freeze.html
I think the problem of mutability is easy to explain in the docs if we can't find a nice fix.

But, by the way, `deepcopy(state)` is science fiction: I have never seen it used in code from our students.

**Comment by Debilski** [comment]
But freezing means that the weights can still change, I think this isn’t sufficient. And people reading the docs is also sci-fi. :)

**Comment by otizonaizit** [comment]
Yes, ok. I mean, let's create the graph at the beginning, attach a copy to `Bot` and if they mess it up they'll find out, and we can point them to the docs if this happens. I still find this better than the current situation, where lots of people are simply regenerating the graph over and over again. And semantically it kind of makes sense to attach it as a static attribut to `Bot`, just like we do with `Bot.walls`.
