### ISSUE TITLE
CI on macos-latest and Python 3.10 and 3.11 is failing all the time

### ISSUE THREAD

**Issue by otizonaizit** [ASPP/pelita#822]
All CI jobs fail on Python 3.10 and 3.11 when run with macos-latest.

I think this problem is not related to pelita but to the CI setup on GitHub or some macos-latest issues.
I suggest to remove these two combinations from the test matrix, or we can't rely on CI for the time being...

**Comment by otizonaizit** [comment]
well, no. Look at the jobs failing here:
https://github.com/ASPP/pelita/pull/821
This is what I was referring to.

**Comment by Debilski** [comment]
Seems to be exactly the test that you touched. The other jobs don’t even run (and fail) because this one failed.

> FAILED test/test_filter_gamestates.py::test_pacman_resets_age - assert [{}, {}] == [{(8, 2): 1}, {}]

**Comment by Debilski** [comment]
To put it differently: Did you run pytest locally before pushing?

**Comment by otizonaizit** [comment]
sorry, mea culpa. I got confused because I am seeing failing macos tests in another project and I simply assumed this is happening here. And got even more confused when github decides to stop other jobs if one fails.
Anyway, fixed now.

**Comment by Debilski** [comment]
It is not impossible of course. We do depend on `macos-latest` and there has been a new macOS release …
