### ISSUE TITLE
Release 2.5.1

### ISSUE THREAD

**Issue by Debilski** [ASPP/pelita#834]
Do we have any blockers or small additions that can make it to 2.5.1 left? Otherwise I’ll release it.

  * 1000 new layouts with dead ends
  * with a 25% chance, a match will be played on a maze with dead ends/chambers
  * Reduced food shadow
  * Streamlined rng handling

**Comment by otizonaizit** [comment]
I don't see any blockers. The PR #832 removal/adjustment of fatal/non-fatal errors is too big of a fish for now. The rest is not urgent. I think you can release.

**Comment by Debilski** [comment]
Closed in #835
