### ISSUE TITLE
Provide a test parcours with ‘weird’ layouts

### ISSUE THREAD

**Issue by Debilski** [ASPP/pelita#97]
In order to make the tournaments’ bots (and also our own demo players) less error prone, we should provide a set of weird layouts. E.g. layouts with unreachable food, layouts where teams have their initial_pos in an unreachable area or on the wrong side; layouts where there are no walls at all.

We should then advise all participants to try those mazes before the tournament so that they can write error-handling code to avoid crashing in these situations.

**Comment by otizonaizit** [comment]
OK, after 7 years we probably agree that people can live without this.
